### PR TITLE
Improvement for receiver mode

### PR DESCRIPTION
**Pull request by proemke**
Changed Frequency Synthesizer Calibration values
Recalculated RX Filter Bandwidth for Message1 and Message2

### CODE REVIEW

**Comment by supersjimmie** [comment]
Can you please explain the expected results from these changes?

**Comment by proemke** [comment]
Limit the bandwidth of the receiver to prevent noise.

Message1:
2*Deviation +Data rate = 2x25 +8  ==> 58kHz. (nearest possible 67.7 Khz) 

Message2:
2*Deviation +Data rate = 2x50 +38 ==> 138kHz. (nearest possible 162.5 Khz) 

And added a check if carrier-sense is above threshold

**Comment by pascalsaul** [comment]
Thanks, this fixed my receiving issues! Only in the last code the changes are different:

void IthoCC1101::initReceive()
    -Data rate         38.3835kBaud
    -RX filter BW      325.000000kHz
    +Data rate           8.00896kBaud
    +RX filter BW        67.708333kHz    

    -Deviation         50.781250kHz
    +Deviation           25.390625kHz

    -writeRegister(CC1101_MDMCFG4 ,0x5A);
    -writeRegister(CC1101_MDMCFG3 ,0x83);
    +writeRegister(CC1101_MDMCFG4 ,0xE8);
    +writeRegister(CC1101_MDMCFG3 ,0x43);

    -writeRegister(CC1101_DEVIATN ,0x50);
    +writeRegister(CC1101_DEVIATN ,0x40);

    -writeRegister(CC1101_FSCAL0 ,0x11);
    +writeRegister(CC1101_FSCAL0 ,0x1F);

    +//writeRegister(CC1101_FSCAL2 ,0x00);

void  IthoCC1101::initReceiveMessage2(IthoMessageType expectedMessageType)
    -writeRegister(CC1101_MDMCFG4 ,0x5A); // set kBaud
    +writeRegister(CC1101_MDMCFG4 ,0x9A); //RX filter BW : 162.500000 Khz Datarate: 38.3835kBaud

    -writeRegister(CC1101_DEVIATN ,0x50);
    +writeRegister(CC1101_DEVIATN ,0x50); //Deviation: 50.781250kHz

**Comment by proemke** [comment]
In the latest release first message is ignored, only the second part of the full message will be received and examined.

**Comment by supersjimmie** [comment]
The current settings work for most people.
Will (need to do) do some testing on my own environment to check if those modified settings also work on a currently working set.

**Comment by supersjimmie** [comment]
Please check or explain the following.
First you say:
```
-writeRegister(CC1101_DEVIATN ,0x50);
+writeRegister(CC1101_DEVIATN ,0x40);
```
But elsewhere you say:
```
-writeRegister(CC1101_DEVIATN ,0x50);
+writeRegister(CC1101_DEVIATN ,0x50); //Deviation: 50.781250kHz
```
So do you mean to set it to 0x40 or leave it to 0x50?

**Comment by proemke** [comment]
For the first part of the full message deviantion must be set @25.390625 Khz  (0x40)
For the second part of the message deviation must be set @50.781250kHz      (0x50)

**Comment by supersjimmie** [comment]
will test it asap.

**Comment by proemke** [comment]
The main reason I check the first message is because it's bandwidth is smaller than the second message.
With a smaller bandwidth less invalid interrupts will be received by the main processor(esp8266/arduino/esp32), only look at the second message with the larger bandwidth if a valid first message has been received.

**Comment by supersjimmie** [comment]
Manually implemented.

**Pull request closed without merging**
